// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BpfMapClientHelloCount = "client_hello_count"
	BpfMapSynackClampCount = "synack_clamp_count"
	BpfMapTcpDropCount     = "tcp_drop_count"
	BpfProgTcEgressFunc    = "tc_egress_func"
	BpfProgTcIngressFunc   = "tc_ingress_func"
	BpfProgXdpRouterFunc   = "xdp_router_func"
)

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TcEgressFunc  *ebpf.ProgramSpec `ebpf:"tc_egress_func"`
	TcIngressFunc *ebpf.ProgramSpec `ebpf:"tc_ingress_func"`
	XdpRouterFunc *ebpf.ProgramSpec `ebpf:"xdp_router_func"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	ClientHelloCount *ebpf.MapSpec `ebpf:"client_hello_count"`
	SynackClampCount *ebpf.MapSpec `ebpf:"synack_clamp_count"`
	TcpDropCount     *ebpf.MapSpec `ebpf:"tcp_drop_count"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	ClientHelloCount *ebpf.Map `ebpf:"client_hello_count"`
	SynackClampCount *ebpf.Map `ebpf:"synack_clamp_count"`
	TcpDropCount     *ebpf.Map `ebpf:"tcp_drop_count"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.ClientHelloCount,
		m.SynackClampCount,
		m.TcpDropCount,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TcEgressFunc  *ebpf.Program `ebpf:"tc_egress_func"`
	TcIngressFunc *ebpf.Program `ebpf:"tc_ingress_func"`
	XdpRouterFunc *ebpf.Program `ebpf:"xdp_router_func"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TcEgressFunc,
		p.TcIngressFunc,
		p.XdpRouterFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpf.o
var _BpfBytes []byte
