package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// startVPN brings up the configured VPN tunnel and returns the active uplink interface name.
func startVPN(cfg *Config, runDir string) (string, error) {
	if !cfg.EnableVPN {
		return cfg.Uplink, nil
	}

	mode := strings.ToLower(cfg.VPNMode)
	switch mode {
	case "wireguard", "warp":
		confPath := cfg.VPNConfig
		if mode == "warp" && !fileExists(confPath) {
			logInfo("WARP VPN config not found at %s, generating automatic profile template...", confPath)
			if err := generateWARPConfig(confPath); err != nil {
				return "", fmt.Errorf("failed to generate WARP profile template: %w", err)
			}
		}

		if !fileExists(confPath) {
			return "", fmt.Errorf("VPN configuration file not found at %s", confPath)
		}

		logInfo("starting WireGuard VPN tunnel using %s", confPath)
		// Use wg-quick to bring up the interface
		out, err := runCmd("wg-quick", "up", confPath)
		if err != nil && !strings.Contains(out, "already exists") {
			return "", fmt.Errorf("cannot start WireGuard VPN (%s): %s", confPath, strings.TrimSpace(out))
		}

		// Write tracking file to know wg-quick was started by routerd
		_ = os.WriteFile(filepath.Join(runDir, "vpn_started"), []byte(confPath), 0600)

		iface := deriveInterfaceFromConf(confPath, cfg.VPNInterface)
		logInfo("WireGuard VPN active on interface %s", iface)
		return iface, nil

	case "custom":
		if cfg.VPNInterface == "" || cfg.VPNInterface == "auto" {
			return "", fmt.Errorf("VPN_INTERFACE must be specified when VPN_MODE=custom (e.g. wg0, tun0)")
		}
		logInfo("using custom existing VPN interface %s as uplink", cfg.VPNInterface)
		return cfg.VPNInterface, nil

	case "dpibypass":
		logInfo("DPI Bypass mode enabled (TCP SNI fragmentation & MSS clamping active)")
		return cfg.Uplink, nil

	default:
		return "", fmt.Errorf("unsupported VPN_MODE %q (use wireguard, warp, custom, or dpibypass)", cfg.VPNMode)
	}
}

// stopVPN brings down the VPN tunnel if it was started by routerd.
func stopVPN(cfg *Config, runDir string) {
	if data, err := os.ReadFile(filepath.Join(runDir, "vpn_started")); err == nil {
		confPath := strings.TrimSpace(string(data))
		if confPath != "" {
			logInfo("stopping WireGuard VPN tunnel (%s)", confPath)
			_, _ = runCmd("wg-quick", "down", confPath)
		}
		_ = os.Remove(filepath.Join(runDir, "vpn_started"))
	}
}

func deriveInterfaceFromConf(confPath, defaultIface string) string {
	base := filepath.Base(confPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	if name != "" {
		return name
	}
	if defaultIface != "" {
		return defaultIface
	}
	return "wg0"
}

// generateWARPConfig generates a basic WireGuard profile template for Cloudflare WARP.
func generateWARPConfig(path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	content := `# Cloudflare WARP / Generic WireGuard VPN Profile Template
# Generated by routerd

[Interface]
# PrivateKey = YOUR_PRIVATE_KEY
# Address = 172.16.0.2/32, 2606:4700:110:8f2e:80b7:5d63:9b65:e594/128
# DNS = 1.1.1.1, 1.0.0.1

[Peer]
# PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
# Endpoint = 162.159.192.1:2408
# AllowedIPs = 0.0.0.0/0, ::/0
`
	return os.WriteFile(path, []byte(content), 0600)
}
